Added captureCanvas method
jgradim/react-user-media pull request #5
Opened 2016-10-06 02:51 UTC by olalonde

This can be useful to call webcam.captureCanvas().toBlob for example.

2016-11-01 12:21 UTC, jgradim requested changes
Please remove the commit where you modify `package.json`, I have this setup like this to ensure we're using local versions of the packages, with versions defined in `package.json`

2016-11-01 12:21 UTC, jgradim commented on src/webcam/index.js
> +      return canvas
Missing `;`

2016-11-01 12:21 UTC, jgradim commented
Oh, and thank you for the contribution! 😄

2016-11-01 20:47 UTC, olalonde commented
> Please remove the commit where you modify package.json

It still does that, the `./node_modules/.bin` directory is the first place npm looks for binary so it's not necessary to explicitly write it. See https://docs.npmjs.com/misc/scripts#path

2016-12-07 22:26 UTC, jgradim approved these changes

2016-12-07 22:26 UTC, merged

2016-12-07 22:29 UTC, jgradim commented
@olalonde Sorry for the delay on this! Also published `0.1.7` to npm